name: docker-build
on:
  # release:
  #   types:
  #     - created
  #     - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build-amd64:
    name: build-amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          cache-to: type=gha,dest=/tmp/.buildx-cache
          cache-from: type=gha,src=/tmp/.buildx-cache

  # docker-build-arm64:
  #   name: build-arm64
  #   runs-on: blacksmith-2vcpu-ubuntu-2204-arm
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Login to ghcr.io
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ secrets.GHCR_USERNAME }}
  #         password: ${{ secrets.GHCR_TOKEN }}
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Docker Build
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
  #         build-args: |
  #           COMMIT_SHA=${{ github.sha }}
  #         platforms: linux/arm64
  #         context: .
  #         file: ./Dockerfile
  #         cache-to: type=gha,dest=/tmp/.buildx-cache
  #         cache-from: type=gha,src=/tmp/.buildx-cache